# Generated by Django 5.1.3 on 2024-11-28 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_workout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='user',
        ),
        migrations.AddField(
            model_name='workout',
            name='workout_type',
            field=models.CharField(choices=[('strength', 'Strength'), ('cardio', 'Cardio'), ('flexibility', 'Flexibility')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
